FROM mcr.microsoft.com/dotnet/aspnet:5.0 as base
WORKDIR /dockerapp
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:5.0 as build
WORKDIR /dockersrc
COPY RestfulApiVisualCode.csproj .
RUN dotnet restore RestfulApiVisualCode.csproj

COPY . .
WORKDIR /dockersrc
RUN dotnet build RestfulApiVisualCode.csproj -c Release -o /dockerapp 

FROM build as publish
RUN dotnet publish RestfulApiVisualCode.csproj -c release -o /dockerapp

FROM base as final
WORKDIR /dockerapp
COPY --from=publish /dockerapp .
ENTRYPOINT ["dotnet","RestfulApiVisualCode.dll"]



