// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestfulApiVisualCode.DataBaseContext;

namespace RestfulApiVisualCode.Migrations
{
    [DbContext(typeof(EventsContext))]
    [Migration("20220310210454_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("RestfulApiVisualCode.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dateofevent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discribeevent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fixevent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isserios")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nameofasb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nameofdevice")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Dateofevent = "3/11/2022",
                            Discribeevent = "ваще коллапс",
                            Fixevent = "все пофиксили",
                            Isserios = "серьезно",
                            Nameofasb = 1,
                            Nameofdevice = "SSL"
                        },
                        new
                        {
                            EventId = 2,
                            Dateofevent = "3/11/2022",
                            Discribeevent = "все сломалось",
                            Fixevent = "это не",
                            Isserios = "не серьезно",
                            Nameofasb = 2,
                            Nameofdevice = "Karrera"
                        },
                        new
                        {
                            EventId = 3,
                            Dateofevent = "3/11/2022",
                            Discribeevent = "ваще коллапс",
                            Fixevent = "все пофиксили",
                            Isserios = "не серьезно",
                            Nameofasb = 7,
                            Nameofdevice = "микрофон"
                        },
                        new
                        {
                            EventId = 4,
                            Dateofevent = "3/11/2022",
                            Discribeevent = "жесть какая",
                            Fixevent = "это не",
                            Isserios = "серьезно",
                            Nameofasb = 5,
                            Nameofdevice = "Karrera"
                        });
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subheader")
                        .HasColumnType("TEXT");

                    b.HasKey("PageId");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            PageId = 1,
                            Header = "Видеопульт",
                            Info = "Вот тут написано как делать окна и всякие эффекты",
                            Subheader = "Эффекты, окна"
                        },
                        new
                        {
                            PageId = 2,
                            Header = "Видеопульт",
                            Info = "Вот тут сбор всяких поломок",
                            Subheader = "Разного рода поломки"
                        },
                        new
                        {
                            PageId = 3,
                            Header = "Камеры, CCU и OCP",
                            Info = "Вот тут написано о великой полезности камер",
                            Subheader = "Камеры"
                        },
                        new
                        {
                            PageId = 4,
                            Header = "Звуковое оборудование",
                            Info = "Вот здесь написано про микрофоны и их особенности",
                            Subheader = "Микрофоны"
                        });
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Login = "Timmy",
                            Password = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
