// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestfulApiVisualCode.DataBaseContext;

namespace RestfulApiVisualCode.Migrations
{
    [DbContext(typeof(EventsContext))]
    [Migration("20220723165739_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("RestfulApiVisualCode.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dateofevent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discribeevent")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventCreator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fixevent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isserios")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nameofasb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nameofdevice")
                        .HasColumnType("TEXT");

                    b.Property<string>("tags")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageByte")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.HasIndex("EventId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageCreator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subheader")
                        .HasColumnType("TEXT");

                    b.Property<string>("tags")
                        .HasColumnType("TEXT");

                    b.HasKey("PageId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Engeneer"
                        });
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Login = "Admin",
                            Password = "Admin",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.Image", b =>
                {
                    b.HasOne("RestfulApiVisualCode.Models.Event", "EventforImage")
                        .WithMany("EventImages")
                        .HasForeignKey("EventId");

                    b.Navigation("EventforImage");
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.User", b =>
                {
                    b.HasOne("RestfulApiVisualCode.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.Event", b =>
                {
                    b.Navigation("EventImages");
                });

            modelBuilder.Entity("RestfulApiVisualCode.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
